[mongodb]
mongo-01 ansible_host=172.31.66.74  mongodb_role=primary
mongo-02 ansible_host=172.31.68.157 mongodb_role=secondary
mongo-03 ansible_host=172.31.67.144 mongodb_role=secondary
mongo-04 ansible_host=172.31.67.224 mongodb_role=secondary
mongo-05 ansible_host=172.31.67.134 mongodb_role=secondary

[mongodb:vars]
ansible_user=ubuntu
ansible_become=yes
ansible_python_interpreter=/usr/bin/python3
